server:
  port: 3000
  servlet:
    context-path: /api

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: user
    password: password
    url: jdbc:h2:mem:global-kinetic
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
